import Head from "next/head";
import Image from "next/image";
import { Open_Sans } from "next/font/google";
import AppLayout from "@/components/AppLayout";

const openSans = Open_Sans({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen py-10 bg-gray-100">
      <AppLayout />
      </div>
    </>
  );
}
